title: Subnet page
description: A community owned and maintained page for documenting subnets on Avalanche.
theme: just-the-docs

url: https://subnet.page

aux_links:
  Template Repository: https://github.com/avalanchepage/subnet.page

plugins:
  - jekyll-default-layout
